config/routes.rb
Planting::Application.routes.draw do
  
  root :to => "answers#home"
  
  match 'answers/linux' => 'answers#linux', :as => "linux"
  match 'answers/git' => 'answers#git', :as => "git"
  match 'answers/css' => 'answers#css_usage', :as => "css"
  match 'answers/weather' => 'answers#google_api', :as => "weather"
  match 'answers/files' => 'answers#files_operations', :as => "files"
  match 'answers/users' => 'answers#duplicated_users', :as => "dup_users"
  
  match 'introductions/why' => 'introductions#why', :as => "why"
  match 'introductions/basic_info' => 'introductions#basic_info', :as => "basic_info"
  match 'introductions/showcase' => 'introductions#showcase', :as => "showcase"
  
  match 'users/delete_duplicate' => 'users#delete_duplicate', :as => 'delete_duplicate'  
  
  resources :users
  

end

app/models/user.rb
class User < ActiveRecord::Base
end

# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  email      :string(255)
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/models/weather.rb
class Weather
  include HTTParty
  base_uri 'http://www.google.com/ig/api?weather='
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def linux
  end
  
  def git
  end
  
  def css_usage
  end
  
  def google_api
    # return a hash structure
    results = Weather.get('Hangzhou')
    @current = results["xml_api_reply"]["weather"]["current_conditions"]
    @forecasts = results["xml_api_reply"]["weather"]["forecast_conditions"]
  end
  
  def files_operations
  end
  
  def duplicated_users
    @users = User.all
  end
  
  def home
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale
  
  protected
    def set_locale
      I18n.locale = params[:locale] unless params[:locale].blank?
    end
end

app/controllers/introductions_controller.rb
class IntroductionsController < ApplicationController
  
  def basic_info
  end
  
  def showcase
  end
  
  def why
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new 
    respond_to do |format|
      format.js
    end
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js {render 'fail_create.js.haml'}
      end
    end
  end
  
  def delete_duplicate
    User.delete_all(["id NOT IN (?)", 
        User.select('min(id) as id').group(:email).map(&:id)])
      
    @users = User.all
    respond_to do |format|
      format.js
    end
  end
  
  
end

app/helpers/answers_helper.rb
module AnswersHelper
  def convert_fahrenheit(degree)
    (degree-32)*5/9
  end
end

app/helpers/application_helper.rb
#encoding: UTF-8
module ApplicationHelper
  
  def language_selecotr
    if I18n.locale == :en
      link_to "Chinese", url_for(:locale => 'cn')
    else
      link_to "英 语", url_for(:locale => 'en')
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/css_usage.html.haml
%h4
  .box
    .question_box Q
    Use CSS and HTML to write a layout of Header, Left side bar, and Main content layout, header and main content width needs to change with browser width and needs to have conformable margin and padding, and background color should be red, green, blue, Should work on Safari, Chrome, Firefox, IE 6, 7, 8       
  
  %p
    Demo:
    = link_to "Pure CSS and HTML layout ", "/layout.html", :target => "_blank"
  
  .box 
    .question_box Q
    Use jQuery to create the above HTML and CSS layout dynamically without using whole chunk of html and css code
  Demo:
  = link_to "Build layout through jQuery", "/jlayout.html", :target => "_blank"

app/views/answers/duplicated_users.haml
%h4
  .box 
    .question_box Q
    Suppose we have User table that have duplicate email records, Use Rails 3 ActiveRecord to write a program to delete duplicated email records that are younger
    
    

%h4
  %p 
    Following is the demo(using ajax) which you could add any user and finally delete duplicated users. 
    = button_to "Delete duplicate", delete_duplicate_path(:format => :js), |
      :method => :post, :remote => true
      
  .clearfix
    #all_users.notice
      %table
        %caption 
          All user records 
          %strong before 
          deleting 
        %tbody
          %tr
            %th ID
            %th Name
            %th Email      
          = render @users
    
    #delete_duplicate.notice
      %table
        %caption 
          All user records 
          %strong after 
          deleting
        %tbody
          %tr
            %th ID
            %th Name
            %th Email

  #new_user

  = link_to "new user", new_user_path(:format => :js), :remote => true, :id => "new_user_link"
  
  
  %p
  Main ruby code:
  .notice 
    User.delete_all(["id NOT IN (?)", User.select('min(id) as id').group(:email).map(&:id)])
  
  %br
  
  .box 
    .question_box N
    While I'm using the free hosting service of Heroku, the processing speed may be not so well. Please be patient after doing some operations.

app/views/answers/files_operations.html.haml
%h4.box 
  .question_box Q  
  Use one of these languages Ruby／Python／Objective C／C／Google Go, Write a program to read text file of 2000 lines, and do sort on the first character of the each line, and write to a new text file.

%h4
  Ruby code:

  .notice
    File.open("new.txt", "w") do |file|
    %br
      %span.indent
        file.puts File.readlines("2000Lines.txt").sort_by{ |line| line[0]}
    end

app/views/answers/git.html.haml
%h4
  .box
    .question_box Q
    Do you have a github/google code account? If so, what's your github/google code name?
  %p 
    My github account name is 
    = link_to "kobeld", "https://github.com/kobeld", :target => "_blank"
    
  .box
    .question_box Q
    What is the Linux Kernel repository address?
  %p
    = link_to "Here", "http://github.com/mirrors/linux-2.6", :targe => "_blank"
    is the Linux kernel repository 
    

  .box
    .question_box Q
    What are the git commands that will be used when committing changes to Linux Kernel source repository?

  1. Fork the "Linux Kernel" repository in Github.

  %p 
  2. Clone the remote "Linux Kernel" project to local machine.
  .notice
    $ git clone git@github.com:kobeld/linux-2.6.git
    %br
    $ cd linux-2.6.git

  %p 
  3. Add remote configuration
  .notice
    $ git remote add upstream git://github.com/mirrors/linux.git

  %p
  4. Before modifying, create and switch to a new branch
  .notice
    $ git checkout -b modified-linux

  %p
  5. Commit changes to local repository
  .notice
    $ git commit -am "changed some files"

  %p
  6. Merge the branch
  .notice
    $ git checkout master
    %br
    $ git merge modified-linux

  %p
  7. Update from the original repo
  .notice
    $ git fetch upstream master
    %br
    $ git merge upstream/master

  %p
  8. Commit to Github
  .notice
    $ git push origin master

  %p
  9. Wishing to contribute
  %br 
    Send pull request to the author in Github.

  %p

app/views/answers/google_api.html.haml
%h4
  .box
    .question_box Q  
    Use one of Ruby／Python／Objective C／C／Google Go + Google API to print the weather report of Hangzhou of the day after tomorrow

#mapRegion
%p

%h4
  For the sake of conenience, I use 
  = link_to "httparty gem", "https://github.com/jnunemaker/httparty", :target => "_blank" 
  instead of raw ruby net::http class to make http easy.
  %p
  .notice
    class Weather
    %ul.code
      %li include HTTParty
      %li base_uri 'http://www.google.com/ig/api?weather=' 
    end
    
  .notice
    def google_api
    %ul.code
      %li results = Weather.get('Hangzhou')
      %li @current = results["xml_api_reply"]["weather"]["current_conditions"]
      %li @forecasts = results["xml_api_reply"]["weather"]["forecast_conditions"]
    end
  
#weather_div
  %h3
    The Plant
    %span{:style => "font-size: 0.7em; color: gray"} in Hangzhou
  
  %div{:style => "float:left"}
    = image_tag "http://www.google.com/#{raw @current["icon"]["data"]}"

  %div{:style => "float:left; font-size:2em; margin: 0 0.5em; height:50px"}
    = "#{@current["temp_c"]["data"]} °C"

  %div
    = "Current: #{@current["condition"]["data"]}"
    %br
    = "Wind: #{@current["wind_condition"]["data"]}"
    %br
    = "Humidity: #{@current["humidity"]["data"]}"

  - @forecasts.each do |forecast|
    %div{:style => "float:left; text-align: center; margin-right: 2em"} 
      = forecast["day_of_week"]["data"]
      %br
      = image_tag "http://www.google.com/#{raw forecast["icon"]["data"]}"
      %br
      = "#{convert_fahrenheit(forecast["low"]["data"].to_i)}° | "
      = "#{convert_fahrenheit(forecast["high"]["data"].to_i)}°"


:plain
  <script src="http://ditu.google.cn/maps/api/js?v=3&sensor=false" 
      type="text/javascript"></script>

:javascript
  $(function(){
    var popup_content = $("#weather_div").html();
    var phantLatlng = new google.maps.LatLng(30.273375, 120.137303);
    var mapCenter = new google.maps.LatLng(30.315, 120.137303);
    var myOptions = {
      zoom: 12,
      center: mapCenter,
      streetViewControl: false,
      scaleControl: false,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var map = new google.maps.Map(document.getElementById("mapRegion"), myOptions);
    new google.maps.Marker({
      map: map,
      position: phantLatlng
    });
    
    var poiMarker = new google.maps.Marker({
      position: phantLatlng,
      map: map
    });
  
    var poiInfoWindow = new google.maps.InfoWindow({
      content:popup_content
    });

    poiInfoWindow.open(map,poiMarker);
  });

app/views/answers/home.html.haml
%h4
  .box
    .question_box
      Hi
    %h3 
      My name is 
      = link_to "Dong Liang", basic_info_path
      = "."
    
    The regular way of answering  
    = link_to "the Plant test ", "http://tinyurl.com/theplant-test", :target => "_blank"
    is boring. So I took some time to build this small site to make it more funny and interactive.
    
    %p
    Also, though I'm not an experienced ROR developer(but Java field), this represents my sincere heart that I'm looking forward to make web development base upon Ruby on Rails to be my career path.
    
    %p
    Finally, in my opinion, programming using Ruby/Rails is really happy. Just like what Matz says... XD 
  .list_box.clearfix
    This site is built with 
    %strong Rails 3.0.9 
    and ...
    %br/
    %dl
      %dt CSS framework: 
      %dd Compass
      %dt View template:
      %dd Haml
      %dt JS library:
      %dd JQuery
      %dt API resources:
      %dd Google Map/Weather API
      %dt Editor: 
      %dd Textmate
      %dt Hosting:
      %dd Heroku
      %dt Github: 
      %dd= link_to "https://github.com/kobeld/planting" 

app/views/answers/linux.html.haml
%h4
  .box
    .question_box Q 
    You can only operate on one local Linux system, Please write a command to copy a local file to a remote linux server, and the command for remove it

.list_box.clearfix
  Assumptions:
  %br/
  %dl
    %dt local file: 
    %dd ~/doc/abc.txt
    %dt server name: 
    %dd kobeld
    %dt server address: 
    %dd 192.168.1.100
    %dt target directory: 
    %dd /files/


%h4
  1. Copy a local file to remote linux server
  .notice
    $ scp ~/doc/abc.txt kobeld@192.168.1.100:/files/

  %p
  2. Delete the local file
  .notice
    $ rm ~/doc/abc.txt

app/views/introductions/basic_info.html.haml
.box
  %h2 
    %strong= t("basic_info.name")
    .languages
      = t("basic_info.lang")
      = language_selecotr
  .basic_info.clearfix
    %dl      
      %dt= t("basic_info.label.gender")
      %dd= t("basic_info.content.gender")
      
      %dt= t("basic_info.label.birthday")
      %dd 1984-03
      
      %dt= t("basic_info.label.location")
      %dd= t("basic_info.content.location")
      
      %dt= t("basic_info.label.work_experience")
      %dd= t("basic_info.content.work_experience")
  
  %p
  %h3.quiet= t("basic_info.label.education")
  .basic_info.clearfix
    %dl
      %dt= t("basic_info.label.university")
      %dd 
        = link_to t("basic_info.content.university"), "http://www.neu.edu.cn", :target => "_blank"
      
      %dt= t("basic_info.label.degree")
      %dd= t("basic_info.content.degree")
      
      %dt= t("basic_info.label.major")
      %dd= t("basic_info.content.major")
      
      %dt= t("basic_info.label.english")
      %dd= t("basic_info.content.english")
  
  %p    
  %h3.quiet= t("basic_info.label.current_job")
  .basic_info.clearfix
    %dl
      %dt= t("basic_info.label.company")
      %dd
        = link_to t("basic_info.content.company"), "http://www.foryouge.com", :target => "_blank"
      
      %dt= t("basic_info.label.department")
      %dd= t("basic_info.content.department")
      
      %dt= t("basic_info.label.project")
      %dd 
        = link_to t("basic_info.content.project"), showcase_path
      
      %dt= t("basic_info.label.position")
      %dd= t("basic_info.content.position")
      
      %dt= t("basic_info.label.role")
      %dd= t("basic_info.content.role")
  %p
  %h3.quiet= t("basic_info.label.technical_skills")
  .basic_info.clearfix
    %dl
      %dt Ruby
      %dd Ruby on Rails, Haml, Sass/Scss, CoffeeScript
      
      %dt CSS
      %dd Compass, Blueprint
      
      %dt Javascript
      %dd JQuery
      
      %dt Java
      %dd Java EE Architecture including JSF, EJB, JPA, Spring etc.
      
      %dt Linux
      %dd Mac OS, Ubuntu
      
      %dt Editor/IDE
      %dd Textmate, Netbeans, Eclipse/MyEclipse
      
      %dt Tools
      %dd Axure, MindManager, CorelDraw, PhotoShop, MS Visio etc.

  %p    
  %h3.quiet= t("basic_info.label.contact_me")
  .basic_info.clearfix
    %dl
      %dt Email
      %dd kobeld@163.com
      
      %dt= t("basic_info.label.mobile")
      %dd 18665260755
      
      %dt QQ
      %dd 149999265
      
      %dt= t("basic_info.label.others")
      %dd
        = link_to "weibo", "http://weibo.com/kobeld", :target => "_blank"
        = " | "
        = link_to "blog", "http://kobeld.blog.163.com", :target => "_blank"
        = " | "
        = link_to "github", "https://github.com/kobeld", :target => "_blank"
        

app/views/introductions/showcase.html.haml
%h4.box
  TSP is a new thing and not easy to describe in English...

%h3 Foryou TSP 服务平台 (Telematics Service Provider Platform)
%h4
  %span.indent_c 华阳TSP服务平台是华阳将3G无线通信及互联网服务融进汽车电子行业，提供一键导航、车载通讯、驾驶辅助、移动商务、信息娱乐、LBS等多种服务的车载信息系统。
  %br/
  %span.indent_c TSP服务平台由终端设备、服务支撑平台，用户网站系统，坐席系统四部分组成。

= image_tag "overview.png", :title => "TSP overview"

%h3 Foryou TSP坐席系统 (TSP Operator System)

%h4
  %span.indent_c TSP坐席系统构建于华阳客户服务中心、由专属坐席人员来为车主提供365*24小时的不间断语音服务，其中包括POI点查询与目的地发送、TMC实时路况监测以及道路救援等。当用户有需要导航时，只需轻点“一键导航”按钮，车载终端系统便会自动拨通客服中心。此时车主只需说出目的地，坐席人员将远程协助设定，并将信息发回至用户的车载导航系统，不用停车，不用手动输入，即可轻松享受便捷导航。
    
= image_tag "portal.png", :title => "Main page of TSP operator system"

%h4
  %span.indent_c 整个TSP坐席系统采用分层结构设计，从上到下依次分为应用层、表现层、业务逻辑层、持久化层、资源和数据层。应用层面向坐席服务人员，使其通过操作坐席软件客户端来为呼入的车载用户提供服务；表现层主要处理前端页面的展现，将不同系统功能的内容，如GIS地图、当前呼入用户资料与服务状态等组合到一起呈现；业务逻辑层主要是处理业务逻辑，获取各种资源与持久层数据，经过逻辑封装以供表现层调用；持久层主要是对数据进行封装，以便内部进行逻辑处理；资源层包含各种系统服务资源，为上层提供基础的数据服务。

= image_tag "architecture.png", :title => "Architecture of TSP operator system"

.list_box
  %dl
    %dt Architecture:
    %dd Edge Java EE 6 including JSF2, EJB3.1 and JPA2
    
    %dt Front-end:
    %dd Primefaces, JQuery, DWR, CSS, Javascript
    
    %dt 3th party API:
    %dd Google map API & Local search API, MapAbc API, Baidu map API
    
    %dt Web Service: 
    %dd Jaxen RESTful web service
    
    %dt Server:
    %dd Glassfish V3, Tomcat
    
    %dt Database:
    %dd MySQL, Oracle
    
    %dt GIS Development:
    %dd ArcGIS Server 9.3 for Java
    
    %dt IDE:
    %dd NetBeans 6.9, MyEclipse 8.5
    

app/views/introductions/why.html.haml
%h1 This the Kobeld education file

app/views/layouts/_footer.html.haml
%ul
  %li Email: kobeld@163.com
  %li= "|"
  %li Mobile: 18665260755

app/views/layouts/_header.html.haml
.title 
  For the Plant, with the Ruby on Rails...

app/views/layouts/_sidebar.html.haml
%ul
  %li.answer{:style => "font-size: 1.4em; color:#205791 "} 
    The answers
  %li= link_to_unless_current "Welcome", root_path
  %li= link_to_unless_current "Goole Weather", weather_path
  %li= link_to_unless_current "Duplicated users", dup_users_path
  %li= link_to_unless_current "Files operation", files_path
  %li= link_to_unless_current "Git usage", git_path
  %li= link_to_unless_current "Linux usage", linux_path 
  %li= link_to_unless_current "CSS usage", css_path
  %li.about_me{:style => "font-size: 1.4em; color:#205791; margin-top: 0.5em "}
    About me
  %li= link_to_unless_current "Basic info", basic_info_path
  %li= link_to_unless_current "Showcase", showcase_path

app/views/layouts/_stylesheets.html.haml
/[if lt IE 9]
	%script{:src => "http://html5shiv.googlecode.com/svn/trunk/html5.js"}

=stylesheet_link_tag 'screen.css', :media => 'screen, projection'

/[if lt IE 8]
	=stylesheet_link_tag 'ie.css', :media => 'screen, projection'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Planting
    = csrf_meta_tag
    = render 'layouts/stylesheets'
    = javascript_include_tag :defaults
  
  %body.bp.two-col
    #header
      = render "layouts/header"  
    #container
      #sidebar
        = render "layouts/sidebar"
      #content
        = yield
      #footer
        = render "layouts/footer"
      

app/views/users/_form.html.haml
= form_for @user, :remote => true do |f|
  .field
    = f.label :email, "Email"
    = f.text_field :email
  
    .field
    = f.label :name, "Name"
    = f.text_field :name
  
    .actions
    = f.submit "Add user" 
  

app/views/users/_user.html.haml
%tr
  %td= user.id
  %td= user.name
  %td= user.email

app/views/users/create.js.haml
:plain
  $('#all_users table tbody').append("#{escape_javascript(render @user)}");

app/views/users/delete_duplicate.js.haml
:plain
  $("#{escape_javascript(render @users)}").appendTo('#delete_duplicate table tbody');

app/views/users/fail_create.js.haml
alert("Create new user failed!");

app/views/users/new.js.haml
:plain
  $("#{escape_javascript(render 'form')}").insertAfter('#new_user');
  $('#new_user_link').hide();